app:
  title: Potato Plant Disease Detection API
  version: 1.0.0
  description: API for detecting diseases in potato plants
  host: 0.0.0.0
  port: 8000

model:
  path: model/potato_disease_model.h5
  input_size: [224, 224]
  class_names: ["Early Blight", "Late Blight", "Healthy"]
